kind: Deployment
apiVersion: apps/v1
metadata:
  name: slskd
  namespace: p2p
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      initContainers:
      - name: vpn
        image: {{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag }}
        restartPolicy: Always
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        envFrom:
        - secretRef:
            name: slskd-vpn-secret
        env:
        - name: VPN_SERVICE_PROVIDER
          value: nordvpn
        - name: VPN_TYPE
          value: wireguard
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.42.0.0/15"
      - name: verify-vpn
        image: busybox
        command:
        - sh
        - -c
        - |
          sleep 30
          while ! ping -c 1 8.8.8.8; do
            echo "Ping failed, retrying in 5"
            sleep 5
          done
          echo "ping succesfull, exiting"
      containers:
      - name: slskd
        image: {{ .Values.slskd.image.repository }}:{{ .Values.slskd.image.tag }}
        ports:
        - name: web
          containerPort: 5030
        - name: incoming
          containerPort: 50300
        envFrom:
        - secretRef:
            name: slskd-secret
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: AUTO_UPDATE
          value: "false"
        - name: SLSKD_NO_AUTH
          value: "true"
        - name: SLSKD_REMOTE_CONFIGURATION
          value: "true"
        - name: SLSKD_APP_DIR
          value: "/config/slskd"
        - name: SLSKD_DOWNLOADS_DIR
          value: "/downloads/complete"
        - name: SLSKD_INCOMPLETE_DIR
          value: "/downloads/incomplete"
        - name: SLSKD_SHARED_DIR
          value: "/shares"
        - name: SLSKD_LOGS_DIR
          value: /var/log/cerberus
        - name: QUARANTINE_DIR
          value: /quarantine
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: shares
          mountPath: /shares
          readOnly: true
        - name: logs
          mountPath: /var/log/cerberus
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: slskd-config
      - name: shares
        nfs:
          server: ${INFRA_DATA_NFS}
          path: /volume1/data/media/shares
      - name: downloads
        nfs:
          server: ${INFRA_DATA_NFS}
          path: /volume1/data/media/downloads
      - name: logs
        nfs:
          server: ${INFRA_DATA_NFS}
          path: /volume1/kubernetes/logs/prod/slskd
