kind: Service
apiVersion: v1
metadata:
  name: slskd
  namespace: p2p
spec:
  selector:
    app: slskd
  ports:
  - name: http
    port: 5030
    targetPort: 5030
    protocol: TCP
  - name: incoming
    port: 50300
    targetPort: 50300
    protocol: TCP
  type: ClusterIP
