apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: opentelemetry-collector
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.139.0
  releaseName: opentelemetry-collector
  namespace: monitoring
  valuesFile: values.yaml
