apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  repo: oci://quay.io/jetstack/charts
  version: v1.19.3
  releaseName: cert-manager
  namespace: network
  valuesFile: values.yaml

resources:
- external-secret.yaml
- issuer.yaml
- certificate.yaml
- tlsstore.yaml
