apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kiali-operator
  repo: https://kiali.org/helm-charts
  version: 2.21.0
  releaseName: kiali-operator
  namespace: monitoring
  includeCRDs: true
  valuesFile: values.yaml
