cr:
  create: true
  namespace: network
  spec:
    auth:
      strategy: "anonymous"
    external_services:
      prometheus:
        url: "http://prometheus-server.monitoring.svc.cluster.local/"
    server:
      web_fqdn: kiali.${INFRA_DOMAIN}
