cr:
  create: true
  namespace: network
  spec:
    auth:
      strategy: "anonymous"
    external_services:
      prometheus:
        url: "http://prometheus-server.monitoring.svc.cluster.local/"
    deployment:
      ingress:
        enabled: true
        class_name: traefik
        override_yaml:
          metadata:
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
    server:
      web_fqdn: kiali.${INFRA_DOMAIN}
