apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 2.0.0
  releaseName: external-secrets
  namespace: external-secrets
  valuesInline:
    installCRDs: false
    genericTargets:
      enabled: true
    deploymentAnnotations:
      argocd.argoproj.io/sync-wave: '-2'

resources:
- secret-store.yaml
