renovate:
  mendRnvAcceptTos: 'y'
  mendRnvPlatform: 'github'
  config: |
    module.exports = {
      "kubernetes": {
        "fileMatch": ["\\.yaml$"]
      }
    }
  existingSecret: renovate-secret
  mendRnvGithubBotUserId: 'renovate[bot]'
  mendRnvCronJobSchedulerAll: '0 * * * *'
resources:
  requests:
    cpu: 250m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 4Gi
nodeSelector:
  role: worker
