kind: Deployment
apiVersion: apps/v1
metadata:
  name: cwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cwa
  template:
    metadata:
      labels:
        app: cwa
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                - "true"
      containers:
      - name: cwa
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        ports:
        - containerPort: 8083
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: CUSTOM_USER
          valueFrom:
            secretKeyRef:
              name: cwa-secret
              key: USER
        - name: CUSTOM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cwa-secret
              key: PASSWORD
        volumeMounts:
        - name: config
          mountPath: /config
        - name: library
          mountPath: /calibre-library 
        - name: new-books
          mountPath: /cwa-book-ingest
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: calibre-config-pvc
      - name: library
        nfs:
          server: nas.homelab
          path: /volume1/data/media/books/library
      - name: new-books
        nfs:
          server: nas.homelab
          path: /volume1/data/media/books/new
