apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cwa
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`cwa.{{ .Values.domain }}`)
    kind: Rule
    services:
    - name: cwa
      port: 8083
