apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    template:
      data:
        admin-user: admin
        admin-password: "{{ .adminPassword }}"
  data:
  - secretKey: adminPassword
    remoteRef:
      key: /monitoring/grafana
      property: adminPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-config-external-secret
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-config-secret
    template:
      data:
        contactpoints.yaml: |
          apiVersion: 1
          contactPoints:
          - orgId: 1
            name: admin
            receivers:
            - uid: admin
              type: email
              settings:
                addresses: "{{ .adminEmail }}"
                singleEmail: true
              disableResolveMessage: false
  data:
  - secretKey: adminEmail
    remoteRef:
      key: /infra
      property: admin_email
