apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    template:
      data:
        admin-user: admin
        admin-password: "{{ .adminPassword }}"
  data:
  - secretKey: adminPassword
    remoteRef:
      key: /monitoring/grafana
      property: adminPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-smtp-external-secret
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-smtp-secret
  data:
  - secretKey: user
    remoteRef:
      key: /monitoring/grafana
      property: originEmailAuthUser
  - secretKey: password
    remoteRef:
      key: /monitoring/grafana
      property: originEmailAuthPass
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-contact-points-external-secret
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-contact-points-secret
  data:
  - secretKey: CONTACT_POINT_SLACK_RECIPIENT
    remoteRef:
      key: /monitoring/grafana
      property: slackRecipientId
  - secretKey: CONTACT_POINT_SLACK_TOKEN
    remoteRef:
      key: /monitoring/grafana
      property: slackToken
