apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: falco
  repo: https://falcosecurity.github.io/charts
  version: 8.0.0
  releaseName: falcosecurity
  namespace: sec
  valuesFile: values.yaml
