preUpgradeChecker:
  jobEnabled: false

networkPolicies:
  enabled: true

persistence:
  defaultClassReplicaCount: 2
  defaultDataLocality: "best-effort"

longhornManager:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: "NoSchedule"

longhornDriver:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: "NoSchedule"

defaultSettings:
  taintToleration: role=cp:NoSchedule

defaultBackupStore:
  backupTarget: "nfs://nas.homelab:/volume1/${INFRA_ENV}/backup/longhorn"
