preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClassReplicaCount: 2

longhornManager:
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"

longhornDriver:
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"

defaultBackupStore:
  backupTarget: "nfs://nas.homelab:/volume1/${INFRA_ENV}/backup/longhorn"
