apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../

helmCharts:
- name: traefik
  repo: "https://traefik.github.io/charts"
  version: 39.0.1
  releaseName: traefik
  namespace: network
  valuesFile: traefik-values.yaml
- name: traefik
  namespace: network
  valuesFile: values.yaml
