apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: network
spec:
#  redirectRegex:
#    regex: ^http://(.*)
#    replacement: https://${1}
#    permanent: true
  redirectScheme:
    scheme: https
    permanent: true