pvc:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  size: 10Gi

deployment:
  image:
    repository: docker.io/jellyfin/jellyfin
    tag: "10.11.6"

backup:
  schedule: "0 15 * * *"
  image:
    repository: busybox
    tag: "1.37"
  command: |
    echo "Starting backup at $(date)"
    tar -czf /backup/jellyfin-$(date +%Y%m%d%H%M%S).tar.gz /config
    echo "Backup completed at $(date)"
    echo "Removing backups older than 3 days"
    find /backup -maxdepth 1 -mtime +3 -type f -delete
