apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: tempo
  repo: https://grafana.github.io/helm-charts
  version: 1.24.0
  releaseName: tempo
  namespace: monitoring
  valuesFile: values.yaml
