apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Media:
        - Jellyfin:
            - abbr: Jellyfin
              href: https://jellyfin.{{ .Values.domain }}
        - Jellyseerr:
            - abbr: Jellyseerr
              href: https://jellyseerr.{{ .Values.domain }}
        - Lidarr:
            - abbr: Lidarr
              href: https://lidarr.{{ .Values.domain }}
        - Sonarr:
            - abbr: Sonarr
              href: https://sonarr.{{ .Values.domain }}
        - Radarr:
            - abbr: Radarr
              href: https://radarr.{{ .Values.domain }}
    - Monitoring:
        - Grafana:
            - abbr: Grafana
              href: https://grafana.{{ .Values.domain }}
    - Development:
        - Jenkins:
            - abbr: Jenkins
              href: https://jenkins.{{ .Values.domain }}
        - Github:
            - abbr: Github
              href: https://github.com/home-kops
  services.yaml: |
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.{{ .Values.domain }}
            description: Watch movies and TV shows.
            widget:
              type: jellyfin
              url: https://jellyfin.{{ .Values.domain }}
              key: {{ .Values.jellyfinApiKey }}
              enableBlocks: true
              enableNowPlaying: true
              enableUser: true
              showEpisodeNumber: true
              expandOneStreamToTwoRows: false
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
