deployment:
  nodeSelector:
    size: s
  image:
    repository: ghcr.io/gethomepage/homepage
    tag: v1
  replicas: 1

domain: <path:secret/data/infra#domain>
jellyfinApiKey: <path:secret/data/misc/homepage#jellyfinApiKey>
