apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: prometheus
  repo: oci://ghcr.io/prometheus-community/charts
  version: 28.9.1
  releaseName: prometheus
  namespace: monitoring
  valuesFile: values.yaml
  additionalValuesFiles:
  - jobs.yaml
