kubeProxyReplacement: true

k8sServiceHost: ${INFRA_HA_VIP}
k8sServicePort: 6443

socketLB:
  enabled: true
  hostNamespaceOnly: true

cni:
  exclusive: false

operator:
  replicas: 1

l2announcements:
  enabled: true

externalIPs:
  enabled: true

devices: "eth0"

k8sClientRateLimit:
  qps: 32
  burst: 64

gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"

hubble:
  relay:
    enabled: true
    prometheus:
      enabled: true
  ui:
    enabled: true
