kubeProxyReplacement: false

# socketLB:
#   enabled: false
#   hostNamespaceOnly: true

cni:
  exclusive: false

operator:
  replicas: 1

tolerations:
- key: "role"
  operator: "Equal"
  value: "cp"
  effect: "NoSchedule"

envoy:
  tolerations:
  - operator: "Exists"
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"
