kubeProxyReplacement: true

k8sServiceHost: 192.168.10.50
k8sServicePort: 6443

socketLB:
  enabled: true
  hostNamespaceOnly: true

cni:
  exclusive: false

operator:
  replicas: 1

l2announcements:
  enabled: true

externalIPs:
  enabled: true

k8sClientRateLimit:
  qps: 32
  burst: 64

gatewayAPI:
  enabled: true
