apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: devops-tools
spec:
  project: default
  source:
    repoURL: https://github.com/home-kops/argocd-config.git
    targetRevision: main
    path: ./<path:secret/data/infra#env>
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
