apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 9.4.2
  releaseName: argocd
  namespace: devops-tools
  valuesFile: values.yaml

resources:
- external-secrets.yaml
- application.yaml
